// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPB2Fh33PYG9NPXo1_hQBEbsgar2193Fg',
    appId: '1:344604724259:web:a894d3201205ecd585b596',
    messagingSenderId: '344604724259',
    projectId: 'bondingbowls-dc28d',
    authDomain: 'bondingbowls-dc28d.firebaseapp.com',
    storageBucket: 'bondingbowls-dc28d.firebasestorage.app',
    measurementId: 'G-GYPBSE7K3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs6Fn32xBxPbfCLfbUliwz2oqnok7_xgc',
    appId: '1:344604724259:android:4efb584665c4b2d785b596',
    messagingSenderId: '344604724259',
    projectId: 'bondingbowls-dc28d',
    storageBucket: 'bondingbowls-dc28d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Gd2us2UO6MpOl8d_7Tg1kF-jFVulB7Y',
    appId: '1:344604724259:ios:1fdc6b3bbbde69e285b596',
    messagingSenderId: '344604724259',
    projectId: 'bondingbowls-dc28d',
    storageBucket: 'bondingbowls-dc28d.firebasestorage.app',
    iosBundleId: 'com.example.convoHearts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Gd2us2UO6MpOl8d_7Tg1kF-jFVulB7Y',
    appId: '1:344604724259:ios:1fdc6b3bbbde69e285b596',
    messagingSenderId: '344604724259',
    projectId: 'bondingbowls-dc28d',
    storageBucket: 'bondingbowls-dc28d.firebasestorage.app',
    iosBundleId: 'com.example.convoHearts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPB2Fh33PYG9NPXo1_hQBEbsgar2193Fg',
    appId: '1:344604724259:web:17ce12d231f2491385b596',
    messagingSenderId: '344604724259',
    projectId: 'bondingbowls-dc28d',
    authDomain: 'bondingbowls-dc28d.firebaseapp.com',
    storageBucket: 'bondingbowls-dc28d.firebasestorage.app',
    measurementId: 'G-N67VMF4GTR',
  );

}